### PR TITLE
Enemy spawner + other stuff

### PR DESCRIPTION
**Pull request by ChatPion**
- add enemy spawners
- add an OAM ID pool 
- handle enemy spawn/despawn when switching rooms
- fix roomgen algorithm
- refactor the collision algorithm (use the same function for the x and y movement)

### CODE REVIEW

**Comment by yberreby** [comment]
The enemy animations are really slow, is this intended?

**Comment by ChatPion** [comment]
Yes if I'm not mistaken, but that can be changed

**Comment by ChatPion** [comment]
Actually no, let me fix that

**Comment by yberreby** [comment]
#62 will fix it

**Comment by AdameBf** [comment]
It's fine, handle this PR first and I'll integrate the changes in #62

**Pull request merged**
